### ISSUE TITLE
Aggregation behaviour needs an overhaul

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1726]
# Problem
## Part 1

Aggregation behaviour is often ambiguous. For example you can set aggregation options at multiple levels:
- In an Impact Function itself
- In the keywords for an aggregation layer
- in the impact function options
- in the global options dialog
- in the code for global defaults

Lets take the following simple scenario as an example:

```
[A flood in Jakarta]
exposure = ../home/timlinux/dev/python/inasafe_data/test/Population_Jakarta_geographic.asc
hazard = ../home/timlinux/dev/python/inasafe_data/hazard/Jakarta_RW_2007flood.shp
function = Flood Evacuation Function Vector Hazard
extent = 106.650081, -6.379716, 107.009482, -6.081757
extent_crs = EPSG:4326
```

With this agregation layer:

```
/home/timlinux/dev/python/inasafe_data/test/kabupaten_jakarta_singlepart.shp
```

**Firstly** the aggregation layer has these keywords:

```

Category postprocessing
Aggregation attribute KAB_NAME
Subcategory aggregation
Title Kabupaten jakarta singlepart
Elderly ratio attribute Global default
Elderly ratio default 0.0
Adult ratio attribute Global default
Female ratio attribute Global default
Youth ratio attribute youthratio
Female ratio default 0.6
Adult ratio default 0.0
```

Note the presence of Adult, Youth etc ratios

**Secondly**, I can also change these rations in the IF options dialog:

![inasafe impact function configuration_012](https://cloud.githubusercontent.com/assets/178003/6779607/785f1a5e-d166-11e4-8eda-3ed288a60a25.png)

**Thirdly** there are defaults defined in : 

`safe/defaults.py:33`

**Fourthly**, global options also defines a female ratio:

![selection_013](https://cloud.githubusercontent.com/assets/178003/6779727/b3c42566-d167-11e4-9ffc-bcabe5975fb7.png)

**Fifthly** some impact functions have specific hard coded defaults (find example).
## Part 2

The second part of this issue relates to the way that the parameters actually interact with each other.

For example in the keywords wizard you can use permutations of layer attributes, fixed values and global defaults (most of which are not editable by the user):

![selection_014](https://cloud.githubusercontent.com/assets/178003/6779888/137b7346-d169-11e4-9209-b08ab518cd36.png)

It is not clear how these options interact - for example what happens if the ration components in the aggregation layer's attribute columns total more or less than 1?
# Proposed solution

Part 1:
- [ ] We need to make it clear for the user how the different aggregation options will interact. Each place where overriding happens should be annotated e.g. on the impact function options dialog, the options could include a note above 'These options will override layer keywords'.
- [ ] We should remove places where the aggregation options  override each other in counter-intuitive ways.
- [ ] We should provide an editor in InaSAFE options where all global defaults can be managed, not just female ratio.

Part 2:

We should re-imagine the keyword setting process for aggregation keywords so that proper constraints are in place to control how the use of an aggregation attribute interacts with global and local defaults. See the illustration below for more detail.

![selection_151](https://cloud.githubusercontent.com/assets/178003/6522617/7c11d632-c419-11e4-8c0c-12722bf5940e.png)
# CC

@Charlotte-Morgan @akbargumbira @Charlotte-Morgan @Jannes123 
# Deployment

I propose that these fixes should make their way into the 'master / stable' version.
