### ISSUE TITLE
Checklist for Flood Realtime v1

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2495]
To Do List for Flood Realtime
- [x] Raster Exposure Population of Jakarta (Jakarta Clipped from World Population) @samnawi  (#2497)
- [x] Vector Exposure Population of Jakarta @samnawi 
- [x] QGIS Map Template of Jakarta for Map PDF @samnawi 
- [x] Investigate PetaJakarta API v2 @lucernae
- [ ] Find Out how to link Report, push shake map to PDC InaWARE @lucernae
- [ ] Code for InaSAFE Flood Realtime processor @lucernae (#2476)

**Comment by samnawi** [comment]
QGIS Map Template of Jakarta for Map PDF #2507

**Comment by samnawi** [comment]
@lucernae Please check in your email, I share you the vector population data (but still at village level --> just for testing)

Thank you.

**Comment by samnawi** [comment]
Just update from discussion with BPBD DKI Jakarta :
**Population Data**
- BPBD DKI will check to Civil and Citizen Agency for the right data.
- DMI and BPBD DKI Jakarta agreed to use population data at village level for now, until we've correct data at RW level.

**Map Template**
- For map template at #2507 will be discussed first by BPBD staff before give the feedback.
- BPBD DKI asks DMI to try to put more information on the map, and let see the complexity from the map.

**IDP %**
- As the my comment at #2448, BPBD DKI Jakarta suggested that more analysis is required to estimate the percentage of IDP --> include in the floodhack analysis data.
- It was noted that in InaSAFE desktop, users can set the evacuation percentage number manually, but in realtime InaSAFE the percentage will be automatic.

**Minimum Needs**
- BPBD DKI requested that minimum needs be calculated per day and not per week. 
- BPBD DKI also requested aggregation by district and minimum needs by district with age groups as per disaster management framework.
- BPBD DKI will supply family data to be used in aggregation.

**Floodhack**
- Will held in early of April 2016.
- Target participant approximately 35 people with various background (GIS, data analyst, demographer, social, etc).
- Prepared some data for this event.

cc : @Charlotte-Morgan @fredychandra @timlinux @lucernae

**Comment by timlinux** [comment]
Closing as this issue has been moved to the dedicated realtime repo.
