### ISSUE TITLE
List of EQ realtime bugs

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2696]
hi @easmetz  - could you please compile a list of all the bugs / issues I gave you for earthquake realtime, link them to the other tickets and please check that the people mentioned are able to supply the relevant information.

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae  - this is for you. I have asked @easmetz to practice writing tickets. Please fix these bugs when the details come through

**Comment by samnawi** [comment]
I add some

- [ ]  [Realtime] Report button problem in Mozilla Firefox #2607 
- [ ]  InaSAFE Realtime EQ: Failed to process non intersected hazard and exposure #2652 
- [ ]  InaSAFE Realtime Shakemap cross referenced with BMKG Website #2651

**Comment by timlinux** [comment]
Here is a more comprehensive list following a review of EQ issues with @lucernae 

-[ ] Indonesian population data points and place names (#2589) @samnawi		
-[ ]Reporting update request status to support cross referencing shake ID with BMKG website (to verify if there are new shakes from BMKG that we have not processed yet). We will do this by polling their service to check for new events.
* Quake has been registered at BMKG
* Shakedata has been uploaded to realtime
* Realtime processing underway
* Processing has completed (success)
* Processing has completed (failure)
-[ ] PDC push is working working Rizky to push to staging PDC site for Charlotte to review#2697 : Filter the earthquakes on the realtime page
-[ ] Filtering on the website (MMI, timeframe, number of records) @samnawi (#2697)
-[ ] #2662 : Smooth the contour lines using code supplied by Hadi & 
-[ ] Indonesian disclaimer on report page - ash (#2698) @adelebearcrozier
-[ ] #1097 Improve test coverage of realtime coverage
-[ ] BMKG shakes sometimes inconsistent (#2717) - Rizky and Iwan to go and meet with BMKG and discuss. The results of your meeting should be fixes to the code or notes added on the about page. Current issues are:
  * Coming very late (may up to 2 hours late)
  * Incorrect shake id if compared with event time (example: event id 20160406150255 but event time actually 2016-04-06 21:45:28, also arrived late)
  * Past shakes sometimes coming (new shakes with past event id)
  * InAWARE got the warning on time, but grid.xml from BMKG arrived late in InaSAFE Realtime (almost 30 mins)
-[ ] Calculate distance for impacted cities and sort from the shortest

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - please keep an eye on this ticket and help with advice on technical requirements if you can

**Comment by timlinux** [comment]
@lucernae just pinging you on this - can you update this issue with whatever has been done and get it closed out if possible?

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi and @lucernae how is this going
