### ISSUE TITLE
Checklist for running tests in QGIS

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2977]
- [ ] Add the test ID (#1, #2 ...)
- [ ] Add coverage
- [ ] Add more outputs from QGIS to make travis happy (error, std)
- [ ] Check the behaviour with the real dock
- [ ] Fix failing tests

**Comment by Gustry** [comment]
Move to 3.6, we would like to polish 3.5

**Comment by Gustry** [comment]
I just discovered why we had some missing tests in the new docker qgis env.
I'm adding new failing tests : 
- [ ] test_integrated_polygon (gui.tools.wizard.test.test_keyword_wizard.WizardDialogTest)
- [ ] test_integrated_line (gui.tools.wizard.test.test_keyword_wizard.WizardDialogTest)
- [ ] test_input_function_centric_wizard_test_4 (gui.tools.wizard.test.test_function_centric_wizard.WizardDialogTest)
- [ ] test_input_function_centric_wizard_test_3 (gui.tools.wizard.test.test_function_centric_wizard.WizardDialogTest)
- [ ] test_input_function_centric_wizard_test_2 (gui.tools.wizard.test.test_function_centric_wizard.WizardDialogTest)
- [ ] test_input_function_centric_wizard (gui.tools.wizard.test.test_function_centric_wizard.WizardDialogTest)
- [ ] test_invalid_keyword_layer (gui.tools.wizard.test.test_keyword_wizard.WizardDialogTest)

in 
- test_function_centric_wizard.py
- test_keyword_wizard.py

**Comment by Gustry** [comment]
See also : https://github.com/inasafe/inasafe/issues/2942
