### ISSUE TITLE
Report v4 roadmap

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3418]
# Beta Release check:

- [x] Architecture support to generate Jinja2 Template
- [x] Architecture support to generate QGIS Composition pdf
- [x] Architecture support for custom composition of elements for Jinja2
- [ ] Working workflow for pdf generation from dock
- [ ] Generic Map report pdf
- [ ] Generic Impact Summary report html and pdf
- [ ] Initial unit testing with control files (working html sample)

# Final Release check

- [ ] Specialized Map Report for edge cases hazard-exposure combination with reporting standard enforced
- [ ] Specialized Impact Summary report for edge cases hazard-exposure combination with reporting standard enforced
- [ ] Infographic element support for Jinja2 Template
- [ ] Infographic element support for QGISComposition
- [ ] Other unthinkable to do list right now

**Comment by timlinux** [comment]
Closing this - reports are in V4 code base - nice work @lucernae !
