### ISSUE TITLE
Report v4 Generic Impact Summary

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3419]
# To do list and roadmap for generic impact summary

## Milestone Checklists

- [ ] Able to render impact function question
- [ ] Able to render impact summary
- [ ] Able to render action checklists
- [ ] Able to render notes
- [ ] Able to render post processors table
- [ ] Able to render aggregation table
- [ ] Able to render minimum needs

### Impact Function Question

Follow this: [Report standard for analysis title](https://github.com/inasafe/inasafe/issues/2920#issuecomment-229865300)
To get the <exposure> and <hazard> just take from the title of the layer

### Impact Summary

This element needed:
- total count of each hazard class (taken from analysis layer fields)
- hazard classification used (taken from hazard layer keywords)
- order of hazard classification to be display (same as above)
- total affected, unaffected and total exposure count (taken from analysis layer keywords)
- total affected, unaffected and total exposure label (will be taken as generic from fields.py)
- the unit of exposure as the column label (**still unsure where to get**)

### Action checklists

Can be taken from exposure.py definitions. Cross ref exposure type from exposure layer keywords.

What about structure with population? Should we display population actions and structure actions?

### Notes

Can be taken from exposure.py definitions. Cross ref exposure type from exposure layer keywords
.
What about structure with population? Should we display population actions and structure notes?

### Minimum Needs

Only display this if exposure type is population (should people too included?). Exposure type is taken from exposure keywords. Profile is taken from MinimumNeeds Profile settings. Profile is needed to render the labels.

### Detailed report (breakdown)

Taken from exposure breakdown layer (csv). Get hazard class from hazard layer keywords classification. Iterate each count field for each exposure type.

### Aggregation report

**Comment by Gustry** [comment]
@lucernae Can we close this ticket ?

**Comment by Gustry** [comment]
This has been done in V4.
