### ISSUE TITLE
Checklist - suggestion for InaSAFE Wizard

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3579]
From our meeting on Monday, 9 January 2016

- [x] Is the max included in the threshold range? Perhaps put < or <= sign,
- [x] Rename Setting as Global Default
- [ ] Fix combo box in field, to show all option at once. #4028 
- [x] Aggregation ID shown in exposure layer keywords. (Fixed in #3577)
- [ ] Add setting to choose currency
- [ ] Make the description lower case in Default Values Setting #4029
- [x] Rename Default values to Global Default
- [x] Group the default values, typo for Eldery in Default Values Setting
- [ ] Explain the value means in feature

From meeting with @Charlotte-Morgan 
- [ ] Rename female ratio —> gender attribute : female ratio
- [x] check to add up to 1 for age ratio
- [x] Set custom max = 1 for ratio
- [ ] Make the question uniform between wizard steps
- [x] Give more description from concepts.py

cc @timlinux it seems you were working on some parts of those items.

**Comment by ismailsunni** [comment]
cc @samnawi and @felix-yew and @ivanbusthomi

**Comment by Charlotte-Morgan** [comment]
Some thoughts on the process of assigning key words to continuous population vector count data with the following attributes: id, village, total_pop, female, youth, adult, elderly.

Stepping through the KW wizard: exposure: population: continuous: count: 
In the next step I think this should ask "Please select the attribute in this layer that represents the **total** number of people"
**Next step**: "Please select attributes in this layer for disaggregated age and gender counts"
- [ ] Age attribute: youth count
- [ ] Age attribute: adult count
- [ ] Age attribute: elderly count
- [ ] Gender attribute: female count

Notes for each to say something like: Attribute containing the number of females.
Drop down to be the definition: Females are wonderful ...

_I suggest that asking for the layer ID and layer name should come at the end of the wizard before the final screen with source data._

Please check drop downs have enough space to display options clearly.

**next screen** only show if one or more attribute in the previous screen was left blank.

Heading: "If your data do not have disaggregated age and gender details; please select age and gender ratios for your population or skip this step to apply the global defaults. "

Any field that has been populated (filled in) in the previous screen should not now ask people for a ratio.
The global defaults should be pre loaded as the default. Users should not be offered a field because the continuous population data can only have counts not ratios as  a unit. 
_the total for the age groups should equal 1 regardless of the number of classes used . ie if the user does not use elderly, youth and adult should equal 1._

Does the concept of feature rate belong in population attributes?? If not - it can be removed from this screen. If it does belong - please move to the next screen along with layer ID and layer name.

@samnawi @timlinux @Gustry - comments welcome :)

**Comment by Charlotte-Morgan** [comment]
The same comment applies to the key words for **aggregation** - however this is a little different because aggregation data do not have units therefore it is possible for someone to have count or ratio data in aggregation layers & possibly a combination of both. ie total_pop count and female ratio in a single layer.

Stepping through the wizard: exposure; aggregation
Is it possible to use the next screen to add both the ID and the names for the aggregation layers?


There is an overlap in the display for the population screen in the wizard for aggregation data
![image](https://cloud.githubusercontent.com/assets/5743135/21923237/73b9456c-d9a5-11e6-945f-00dc65a10850.png)

**Comment by Charlotte-Morgan** [comment]
Please remove the population count and ratio screens from the key words for **buildings.**
Please put the exposure id and feature rate in a screen after the selection of the classes and the remapping screen.

**Comment by Charlotte-Morgan** [comment]
Please remove the population count and ratio screens from the key words for **land cover**
Please add a screen for exposure ID and feature rate as the penultimate screen in the wizard

**Comment by Charlotte-Morgan** [comment]
Please remove the population count and ratio screens from the key words for places. This attribution is not currently supported and there is no plan to document or report against it.  It would be useful to have support for population exposure data as raster, vector poly and vector point in the future; but probably not as a 'place' exposure layer which is about showing the name of a location or airport.
The exposure ID and feature rate could be added as a separate screen however; I am not aware of any plans to calculate post processors on this particular exposure data set.

@Gustry @samnawi @ivanbusthomi  - maybe you have other ideas about Place data?

**Comment by Charlotte-Morgan** [comment]
In the key words wizard for roads; please add the request to identify the exposure ID to the feature rate screen,

**Comment by ismailsunni** [comment]
@ismailsunni will create smaller ticket per check box

**Comment by ismailsunni** [comment]
@ismailsunni make super short term fix for sum == 1

**Comment by timlinux** [comment]
The ratio validation on wizard is a release blocker

**Comment by ismailsunni** [comment]
I have merged my PR #3913 for the release blocker. I will remove the release blocker label in this issue. @Charlotte-Morgan @timlinux

**Comment by ismailsunni** [comment]
From the list in the first comment:
1.  Fix combo box in field, to show all option at once, will be addressed in #4028 
2. Make the description lower case in Default Values Setting, will be addressed #4029
3. Add setting to choose currency, will be parked since there is no use case for now
4. Explain the value means in feature, will be parked since there is no use case for now

**Comment by ismailsunni** [comment]
The other points are covered in #4031 which also cover @Charlotte-Morgan's comment about continuous population vector count data and aggregation layer.

I have checked the other comments are already implemented.

I will close this ticket since all points are fixed or covered in smaller and more specific tickets.
