### ISSUE TITLE
RFC: We should standardize  terminology around impacted, affected, displaced etc.

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3634]
### Problem

Something for the standards doc (and #2920), we should also think about how we report on population and other exposures in terms of what is affected, exposed etc. and the nuances between them. My proposal is we contract a logical framework like this:

![inasafe4 0architecturedetailedarchitecture](https://cloud.githubusercontent.com/assets/178003/22844441/f792c30c-efe6-11e6-9fe5-99711ce00b0e.png)

(draft, for comment)

And then standards all our reporting around this. In the case of population we would have a differentiator between displaced and affected:

* **displaced** - people who had to leave because of an event
* **evacuated** - people who had to leave in anticipation of an event

# Advantages 

By agreeing to adopt this terminology and writing these data to the impact layers, we create the ability to properly validate our algorithms. When the output layers are produced, we can properly validate that the results are consistent both manually and via programmatic testing. We also provide the user with the ability to understand the different elements of the impact.

# Implementation plan

## Change 'affected' in hazard_classifications to a rate

We have seen that in e.g. Aceh quake from December 2017, that exposed features (e.g. buildings) are not uniformly affected by a hazard. We propose that we should use rates (e.g. 90% of buildings will be affected in the high hazard zone) for affected rather than booleans. To start with we can set the rates to 100% for affected areas, but in future these would be reduced based on input from hazard scientists.

```python
        {
            'key': 'medium',
            'value': 3,
            'color': orange,
            'name': tr('Medium hazard zone'),
            'affected': True,
            'description': tr(
                'Water above 1.1m and less than 3.0m. The area is potentially '
                'hit by a tsunami wave with an inundation depth of 1 - 3 '
                'm or equal to V-VI tsunami intensity scale (Papadoupulos and '
                'Imamura, 2001). Tsunami wave with a 3m inundation depth '
                'causes most people frightened and to flee to higher '
                'ground. Small vessels drift and collide. Damage occurs to '
                'some wooden houses, while most of them are safe.'),
            'numeric_default_min': 1,
            'numeric_default_max': 3,
            'citations': [
                {
                    'text': None,
                    'link': None
                }
            ]
        },
```

would become:

```python
        {
            'key': 'medium',
            'value': 3,
            'color': orange,
            'name': tr('Medium hazard zone'),
            'affected': 1.0,   # <-------- concept changed
            'description': tr(
                'Water above 1.1m and less than 3.0m. The area is potentially '
                'hit by a tsunami wave with an inundation depth of 1 - 3 '
                'm or equal to V-VI tsunami intensity scale (Papadoupulos and '
                'Imamura, 2001). Tsunami wave with a 3m inundation depth '
                'causes most people frightened and to flee to higher '
                'ground. Small vessels drift and collide. Damage occurs to '
                'some wooden houses, while most of them are safe.'),
            'numeric_default_min': 1,
            'numeric_default_max': 3,
            'citations': [
                {
                    'text': None,
                    'link': None
                }
            ]
        },
```

## Add the concept of 'exposed' to hazard classifications

We already have the concept of 'affected' in hazard classifications. However we need to add 'exposed' to hazard_classifications so that when we have hazard classes that indicate 'no hazard present here' (e.g. tsunami dry hazard class) we can correctly encode an exposed feature as 'not exposed' (and thus by extension 'not affected'). e.g.:

```python
        {
            'key': 'dry',
            'value': 1,
            'color': green,
            'name': tr('Dry zone'),
            'affected': False,
            'description': tr('No water above ground height.'),
            'numeric_default_min': 0,
            'numeric_default_max': 0.1,
            'citations': [
                {
                    'text': None,
                    'link': None
                }
            ]
        },
```

would become:

```
        {
            'key': 'dry',
            'value': 1,
            'color': green,
            'name': tr('Dry zone'),
            'affected': 0,
            'exposed': True,   # <-------- concept added
            'description': tr('No water above ground height.'),
            'numeric_default_min': 0,
            'numeric_default_max': 0.1,
            'citations': [
                {
                    'text': None,
                    'link': None
                }
            ]
        },
```

## Create additional field generators

Using the logic described in the diagram above,

**Comment by Charlotte-Morgan** [comment]
This RFC needs to be followed by two more:
- [ ] hazard specific displacement rates 
- [ ] how this population exposure terminology relates to DM instruments ie contingency planning, risk assessment and response planning

**Comment by Gustry** [comment]
@timlinux I think we can remove the section `Add the concept of 'exposed' to hazard classifications`. According to @Charlotte-Morgan the all dataset is `exposed`.
The definition of `not exposed` is : 
* no data if the hazard is a raster.
* no polygons if the hazard is a vector layer.

We need to update the diagram to `Exposure Terminology in InaSAFE` because this is not specific to population.

**Comment by lucernae** [comment]
Just to confirm, so features in tsunami dry classes is exposed, but not affected? (because I'm getting confused. :p)

**Comment by Gustry** [comment]
Yes, it is. So i think you need to update the report @lucernae. Let's wait from @Charlotte-Morgan to confirm that we need to update reporting (in the summary analysis)

**Comment by Charlotte-Morgan** [comment]
We need to update the diagram to include all hazard classifications. 
In general:
- Any exposure element (people, builidings, landcover) within the extent of a hazard dataset is exposed.
- Only those exposed elements within certain hazard classes are affected (affected = true)
- Only a percentage of exposed people within each hazard class will be displaced.  Right now we do not know what percentage for each class except for earthquake hazard.
- Min needs are calculated for displaced (even though we don't know what % they are yet :))

**Comment by Charlotte-Morgan** [comment]
@timlinux following review of concepts in #3677 could you please update your beautiful diagram and 
- [ ] replace the word "impacted" with "directly affected" 
- [ ] replace the words "not impacted" with "indirectly affected"

**Comment by Charlotte-Morgan** [comment]
@lrpower - FYI the terminology discussion

**Comment by timlinux** [comment]
@Charlotte-Morgan By the way I have update the diagram accordingly....

**Comment by ismailsunni** [comment]
It seems we already done on this ticket. Should we close it?
