### ISSUE TITLE
Polishing Field Mapping Tool

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4103]
### Problem
The field mapping tool to address #4069 is already in this PR #4094. Most of the functionalities are working. But we can do some polishing before the release. This ticket will list all possible polishing to make the ticket more granullar:

- Write Metadata
    - [x] drag and drop
    - [x] Check spin box is stored properly
    - [x] Save to metadata
    - [x] Unit test for tab and widget
- Read metadata
    - [x] Handle single field name from old keywords
    - [x] Populate field based on metadata
    - [x] Clear used field from the metadata
- Misc
    - [x] Text for description and header text
    - [x] Help page
    - [ ] Better size
    - [x] Filter layer to only show exposure and aggregation layer 
    - [x] Auto select the current selected layer
    - [x] Filter fields —> int and float only
    - [x] Show 10 unique values
- Add to wizard
    - [x] Check the wizard flow #4120
    - [x] Add the step to the wizard #4120
    - [x] Remove unused inasafe fields or default fields
    - [x] Make wizard able to select more than one field for population count #4119 
- Others
    - [x] Show pretty fields in the dock
    - [x] Update definitions.py to list non-group fields
    - [x] Update parameters repository
    - [x] @timlinux to update help definition  #4105
    - [x] Add test layer
    - [x] Add icon for the field mapping tool cc @MariaSolovyeva #4104

**Comment by ismailsunni** [comment]
We can close this now. The size is not high priority.
