### ISSUE TITLE
Polishing Option Dialog

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4113]
### Problem
Current state:
![Option Dialog](https://files.gitter.im/inasafe/inasafe/hfm9/Screen-Shot-2017-04-26-at-9.18.11-AM.png)

Suggestions from @timlinux :
- [x] Tab name: Global Default ->Demographic Defaults  #4121 
- [x] The whole tab content needs to go into a scrollbox widget #4121 
- [ ] If you have time, I think we should tweak the parameters widget so that each input has a little (?) next to the input widget which when clicked will show the extended help_text --> https://github.com/inasafe/parameters/issues/23
- [x] Add basic validation #4126

**Comment by Gustry** [comment]
Nice preview.
Is-it not better having only one scrollbar ? (with Age, Gender, Vulnerability... inside)

**Comment by ismailsunni** [comment]
@Gustry I hope it will be gone when we added scroll bar for the whole widget. Otherwise, I will set it to not use scroll bar. I agree, it's better to have only one.

**Comment by ismailsunni** [comment]
Closing this, since all posible polishing have been implemented
