### ISSUE TITLE
[Realtime Porting] 

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4441]
### Problem
We need to move functionality from InaSAFE realtime to InaSAFE core. E.g.
- [x] Evaluate cardinality : city, distance, and direction from epicentre (related to #4262 )
- [x] Nearest city (related to #4262 )
- [x] Grid converter to tiff file (implemented in InaSAFE)
- [x] Grid to mmi contour with smoothing function using scipy option #4615 
- [x] Multi exposure reporting and the calculation (separated into #4437 #4438 #4439 #4440 )

cc @timlinux @Gustry @myarjunar and @lucernae

**Comment by akbargumbira** [comment]
I have the smoothing work on inasafe project without using scipy unfinished
(haven't tested it). Let me know if it could worth something. I'll clean it
up a bit and commit it.

**Comment by ismailsunni** [comment]
@akbargumbira can you share your work somewhere? and is it fast enough?

**Comment by akbargumbira** [comment]
@ismailsunni check it here (not even tested and separated the convolution function). The gaussian filter is taken from here https://github.com/nicjhan/gaussian-filter/blob/master/gaussian_filter.py (need to give the author credit if it's used at the end)

**Comment by akbargumbira** [comment]
Please compare it to develop branch (I branched it from develop)

**Comment by ismailsunni** [comment]
Thanks @akbargumbira I will check it.

**Comment by ismailsunni** [comment]
All is done, I think we can close this.
