### ISSUE TITLE
Post release todo

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4882]
### Problem

- [ ] Generate manual for http://manual.inasafe.org @ismailsunni  and doc - see https://github.com/inasafe/inasafe/wiki/Updating-manual-inasafe-org and update https://github.com/inasafe/inasafe/wiki/Preparing-a-Release-(On-Release-Day)
- [ ] Generate new API docs, update wiki with procedure at https://github.com/inasafe/inasafe/wiki/Preparing-a-Release-(On-Release-Day) @Gustry 
- [ ] Generate mail chimp group with all previous course attendees and document on https://github.com/inasafe/inasafe/wiki/Preparing-a-Release-(On-Release-Day) - @timlinux
- [ ] Update https://github.com/inasafe/inasafe/wiki/Preparing-a-Release-(On-Release-Day) with link to https://github.com/inasafe/parameters/wiki/Releasing-New-Version-(to-PyPi-and-Github) and @ismailsunni 
- [ ] Update blog and put notes in  https://github.com/inasafe/inasafe/wiki/Preparing-a-Release-(On-Release-Day) @timlinux

### Proposed Solution

**Comment by ismailsunni** [comment]
Done with my part, I have also updated manual for fr and en also.
