### ISSUE TITLE
We need to resolve issues with Zonal Stats in QGIS master

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#617]
# Problem

There are two problems:
## Part 1

Given a simple scenario such as the one below (where red cells have a value of 1 and blue a value of zero):

![quantum gis 1 8 0-lisboa - problem_002](https://f.cloud.github.com/assets/178003/796774/6a0e8e02-ed2f-11e2-9e9f-b6089bc78fe8.png)

Generating zonal stats (the sum and count of cells in a polygon) always returns 0 in QGIS as per the screenshot below.

![attribute table - 1polygonproblem 0 - 3 feature s selected_003](https://f.cloud.github.com/assets/178003/796781/989b53d6-ed2f-11e2-920c-951ce7c8cfd7.png)

This is a problem because is causes aggregation results to be incorrect in many cases.
## Part 2

The zonal stats we have implemented in QGIS is a direct port of the C++ code in QGIS. We need a local implementation as a stop gap until InaSAFE runs on QGIS 2.0. However the python code runs very slowly and needs optimisation. In addition it needs to be able to deal with the edge cases as per the above example.

A sample dataset to replicate is available at  https://dl.dropboxusercontent.com/u/1166848/zproblem.tar.gz
# Proposed solution
- [ ] Debug the zonal stats in QGIS master and implement the appropriate fixes in time for the release of QGIS 2.0
- [ ] Implement unit tests in QGIS 2.0 using the dataset I have provided above to ensure that we do not get regressions in QGIS in the future.
- [ ] Debug the python zonal stats implementation in InaSAFE and ensure that the functionality works there too.
- [ ] Implement unit tests in InaSAFE using the provided dataset to ensure that our native python implementation runs robustly and efficiently.
# Expected Outcome
- Zonal stats should always produce a summary value when some cells intersect with the polygon used for aggregation.
- QGIS 2.0 should be released with working zonal stats
- InaSAFE 1.2 should ship with an interim version of zonal stats implemented in python that works correctly and efficiently.
# CC

@alexbruy 
@simgislab 
@vanpuk 
@mbernasocchi 

We have also made a native zonal stats implementation in Python
